import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from '@/components/Footer'
import Provider from "@/components/Provider";

import { GlobalContextProvider } from "./context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book My Movie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className}  `}
      suppressHydrationWarning={true} >
        <Provider>
        <GlobalContextProvider>
        <Navbar/>
        {children}
        <Footer/>
        </GlobalContextProvider>
        </Provider>
      </body>
    </html>
  );
}
